# Site settings
title: Nick Seagull
email: nikitatchayka@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal site, blog and place for my fantastic,
  development world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nickseagull.github.io" # the base hostname & protocol for your site
twitter_username: CodeSeagull
github_username:  NickSeagull

# Build settings
markdown: kramdown
