name:                gensite
version:             0.0.0.0
github:              "NickSeagull/gensite"
license:             Apache-2.0
author:              "Nikita Tchayka"
maintainer:          "nick@booster.cloud"
copyright:           "2021 Nikita Tchayka"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/NickSeagull/gensite#readme>

dependencies:
- base >= 4.7 && < 5
- hakyll

executables:
  site:
    main:                site.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

