on: [push]
name: build
jobs:
  runhaskell:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'
          enable-stack: true
          stack-version: 'latest'

      - name: Build project
        run: stack build

      - name: Build site
        run: stack exec site build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
