name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRIC_TOKEN }}
          # output_action: none
          config_timezone: "Atlantic/Canary"
          extras_css: |
            * {
              color: #3d4663;
            }
          # Generator config
          config_order: skyline, chess, languages, activity, achievements

          plugin_languages: yes

          plugin_achievements: yes

          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_user: "NickSeagull"
          plugin_chess_platform: lichess.org

          plugin_skyline: yes
          plugin_skyline_frames: 120
          plugin_skyline_quality: 0.8

          plugin_activity: yes

  build:
    needs: github-metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site
        uses: withastro/action@v0
        # with:
        # path: . # The root location of your Astro project inside the repository. (optional)
        # node-version: 16 # The specific version of Node that should be used to build your site. Defaults to 16. (optional)
        # package-manager: yarn # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
